# Rust project justfile — generated by just-just
# https://github.com/casey/just

# Check formatting (no changes)
fmt:
    cargo fmt --check

# Apply formatting
fmt-fix:
    cargo fmt

# Clippy with pedantic lints, warnings denied
clippy:
    cargo clippy --all-targets -- -W clippy::pedantic -D warnings

# Run all tests
test:
    cargo test --all-targets

# Install cargo-crap into this workspace
crap-setup:
    cargo install cargo-crap

# Run cargo-crap with --fail-above for CI gate
crap:
    cargo crap --fail-above

# Full CI pipeline
ci: fmt clippy test crap

# Install a pre-commit hook that runs 'just ci'
install-git-hooks:
    #!/usr/bin/env bash
    set -euo pipefail
    HOOKS_DIR=".githooks"
    mkdir -p "$HOOKS_DIR"
    printf '#!/bin/bash\nset -euo pipefail\necho "==> Running just ci …"\njust ci\n' > "$HOOKS_DIR/pre-commit"
    chmod +x "$HOOKS_DIR/pre-commit"
    git config core.hooksPath "$HOOKS_DIR"
    echo "✓ Git hooks installed — pre-commit will run 'just ci'"
